/*
 * Code for class WEL_SB_CONSTANTS
 */

#include "eif_eiffel.h"
#include "../E1/estructure.h"


#ifdef __cplusplus
extern "C" {
#endif

extern EIF_TYPED_VALUE F1325_14066(EIF_REFERENCE);
extern EIF_TYPED_VALUE F1325_14067(EIF_REFERENCE);
extern EIF_TYPED_VALUE F1325_14068(EIF_REFERENCE);
extern EIF_TYPED_VALUE F1325_14069(EIF_REFERENCE);
extern EIF_TYPED_VALUE F1325_14070(EIF_REFERENCE);
extern EIF_TYPED_VALUE F1325_14071(EIF_REFERENCE);
extern EIF_TYPED_VALUE F1325_14072(EIF_REFERENCE);
extern EIF_TYPED_VALUE F1325_14073(EIF_REFERENCE);
extern EIF_TYPED_VALUE F1325_14074(EIF_REFERENCE);
extern EIF_TYPED_VALUE F1325_14075(EIF_REFERENCE);
extern EIF_TYPED_VALUE F1325_14076(EIF_REFERENCE);
extern EIF_TYPED_VALUE F1325_14077(EIF_REFERENCE);
extern EIF_TYPED_VALUE F1325_14078(EIF_REFERENCE);
extern EIF_TYPED_VALUE F1325_14079(EIF_REFERENCE);
extern EIF_TYPED_VALUE F1325_14080(EIF_REFERENCE);
extern EIF_TYPED_VALUE F1325_14081(EIF_REFERENCE);
extern EIF_TYPED_VALUE F1325_14082(EIF_REFERENCE);
extern EIF_TYPED_VALUE F1325_14083(EIF_REFERENCE);
extern EIF_TYPED_VALUE F1325_14084(EIF_REFERENCE);
extern void EIF_Minit1325(void);

#ifdef __cplusplus
}
#endif


#ifdef __cplusplus
extern "C" {
#endif


#ifdef __cplusplus
}
#endif


#ifdef __cplusplus
extern "C" {
#endif

/* {WEL_SB_CONSTANTS}.sb_lineup */
EIF_TYPED_VALUE F1325_14066 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 0L);
	return r;
}

/* {WEL_SB_CONSTANTS}.sb_lineleft */
EIF_TYPED_VALUE F1325_14067 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 0L);
	return r;
}

/* {WEL_SB_CONSTANTS}.sb_linedown */
EIF_TYPED_VALUE F1325_14068 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 1L);
	return r;
}

/* {WEL_SB_CONSTANTS}.sb_lineright */
EIF_TYPED_VALUE F1325_14069 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 1L);
	return r;
}

/* {WEL_SB_CONSTANTS}.sb_pageup */
EIF_TYPED_VALUE F1325_14070 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 2L);
	return r;
}

/* {WEL_SB_CONSTANTS}.sb_pageleft */
EIF_TYPED_VALUE F1325_14071 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 2L);
	return r;
}

/* {WEL_SB_CONSTANTS}.sb_pagedown */
EIF_TYPED_VALUE F1325_14072 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 3L);
	return r;
}

/* {WEL_SB_CONSTANTS}.sb_pageright */
EIF_TYPED_VALUE F1325_14073 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 3L);
	return r;
}

/* {WEL_SB_CONSTANTS}.sb_thumbposition */
EIF_TYPED_VALUE F1325_14074 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 4L);
	return r;
}

/* {WEL_SB_CONSTANTS}.sb_thumbtrack */
EIF_TYPED_VALUE F1325_14075 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 5L);
	return r;
}

/* {WEL_SB_CONSTANTS}.sb_top */
EIF_TYPED_VALUE F1325_14076 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 6L);
	return r;
}

/* {WEL_SB_CONSTANTS}.sb_left */
EIF_TYPED_VALUE F1325_14077 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 6L);
	return r;
}

/* {WEL_SB_CONSTANTS}.sb_bottom */
EIF_TYPED_VALUE F1325_14078 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 7L);
	return r;
}

/* {WEL_SB_CONSTANTS}.sb_right */
EIF_TYPED_VALUE F1325_14079 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 7L);
	return r;
}

/* {WEL_SB_CONSTANTS}.sb_endscroll */
EIF_TYPED_VALUE F1325_14080 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 8L);
	return r;
}

/* {WEL_SB_CONSTANTS}.sb_horz */
EIF_TYPED_VALUE F1325_14081 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 0L);
	return r;
}

/* {WEL_SB_CONSTANTS}.sb_vert */
EIF_TYPED_VALUE F1325_14082 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 1L);
	return r;
}

/* {WEL_SB_CONSTANTS}.sb_ctl */
EIF_TYPED_VALUE F1325_14083 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 2L);
	return r;
}

/* {WEL_SB_CONSTANTS}.sb_both */
EIF_TYPED_VALUE F1325_14084 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 3L);
	return r;
}

void EIF_Minit1325 (void)
{
	GTCX
}


#ifdef __cplusplus
}
#endif
