/*
 * Generated by ISE 19.05.10.3187 GPL Edition - win64
 */

#include "eif_eiffel.h"
#include "eif_project.h"
#include "egc_include.h"
#include "eoffsets.h"

#ifdef __cplusplus
extern "C" {
#endif
extern void F1_23();
extern EIF_REFERENCE F1_14();
extern void F1559_6605();
extern void F1564_6847();
extern void F919_3187();
extern void F1552_6487();
extern void F380_1233();
extern EIF_REFERENCE F380_1220();
extern EIF_BOOLEAN F380_1232();
extern EIF_BOOLEAN F380_1240();
extern void F380_1242();
extern void F380_1243();
extern void F380_1244();
extern void egc_routine_tables_init (void);

long *eif_area_table = (long *)0;
long *eif_lower_table = (long *)0;
extern char *(*R2[])();
extern char *(*R6[])();
extern char *(*R3[])();

extern char *(*R4[])();

extern char *(*R5[])();



extern void egc_init_plug (void); 
void egc_init_plug (void)
{
	egc_prof_enabled = (EIF_INTEGER) 0;
	egc_correct_mismatch = (void (*)(EIF_REFERENCE)) F1_23;
	egc_twin = (EIF_REFERENCE (*)(EIF_REFERENCE)) F1_14;
	egc_strmake = (void (*)(EIF_REFERENCE, EIF_INTEGER)) F1559_6605;
	egc_str32make = (void (*)(EIF_REFERENCE, EIF_INTEGER)) F1564_6847;
	egc_arrmake = (void (*)(EIF_REFERENCE, EIF_INTEGER, EIF_INTEGER)) F919_3187;
	egc_str_count_offset = + _LNGOFF_1_1_0_2_;
	egc_str_hash_offset = + _LNGOFF_1_1_0_0_;
	egc_str32_count_offset = + _LNGOFF_1_1_0_2_;
	egc_str32_hash_offset = + _LNGOFF_1_1_0_0_;
	egc_routdisp_fl = (void (*)(EIF_REFERENCE, EIF_POINTER, EIF_POINTER, EIF_POINTER, EIF_REFERENCE, EIF_BOOLEAN, EIF_INTEGER)) F1552_6487;
	egc_is_scoop_capable = 1;
	egc_set_exception_data = (void (*)(EIF_REFERENCE, EIF_INTEGER, EIF_BOOLEAN, EIF_INTEGER, EIF_INTEGER, EIF_REFERENCE, EIF_REFERENCE, EIF_REFERENCE, EIF_REFERENCE, EIF_REFERENCE, EIF_REFERENCE, EIF_INTEGER, EIF_BOOLEAN)) F380_1233;
	egc_set_last_exception = (void (*)(EIF_REFERENCE, EIF_REFERENCE)) F380_1232;
	egc_last_exception = (EIF_REFERENCE (*)(EIF_REFERENCE)) F380_1220;
	egc_is_code_ignored = (EIF_BOOLEAN (*)(EIF_REFERENCE, EIF_INTEGER)) F380_1240;
	egc_once_raise = (void (*)(EIF_REFERENCE, EIF_REFERENCE)) F380_1242;
	egc_init_exception_manager = (void (*)(EIF_REFERENCE)) F380_1243;
	egc_free_preallocated_trace = (void (*)(EIF_REFERENCE)) F380_1244;

	egc_str_dtype = 1560;

	egc_str32_dtype = 1564;
	egc_arr_dtype = 918;
	egc_tup_dtype = 1475;
	egc_disp_rout_id = 3246;
	egc_copy_rout_id = 18;
	egc_is_equal_rout_id = 11;

	egc_sp_char = 0x04AE;
	egc_sp_wchar = 0x04B7;
	egc_sp_bool = 0x04B5;
	egc_sp_uint8 = 0x04AD;
	egc_sp_uint16 = 0x04AA;
	egc_sp_uint32 = 0x04B3;
	egc_sp_uint64 = 0x04B6;
	egc_sp_int8 = 0x04B1;
	egc_sp_int16 = 0x04B2;
	egc_sp_int32 = 0x04AF;
	egc_sp_int64 = 0x04B4;
	egc_sp_real32 = 0x04AC;
	egc_sp_real64 = 0x04B0;
	egc_sp_pointer = 0x04AB;
	egc_sp_ref = 0x04A9;

	egc_uint8_dtype = 1499;
	egc_uint16_dtype = 1505;
	egc_uint32_dtype = 1502;
	egc_uint64_dtype = 1514;
	egc_int8_dtype = 1478;
	egc_int16_dtype = 1511;
	egc_int32_dtype = 1508;
	egc_int64_dtype = 1490;
	egc_bool_dtype = 1493;
	egc_real32_dtype = 1481;
	egc_char_dtype = 1487;
	egc_wchar_dtype = 1484;
	egc_real64_dtype = 1496;
	egc_point_dtype = 1550;

	egc_exception_dtype = 423;
	egc_except_emnger_dtype = 379;

	egc_ce_type = egc_ce_type_init;

	egc_ce_exp_type = egc_ce_exp_type_init;
	egc_fsystem = egc_fsystem_init;
	egc_system_mod_init = egc_system_mod_init_init;
	egc_partab = egc_partab_init;
	egc_partab_size = egc_partab_size_init;
	exception_stack_managed = (EIF_BOOLEAN) 0;
	egc_ecreate = (void (**)(EIF_REFERENCE, EIF_REFERENCE)) R2;
	egc_exp_create = (void (**)(EIF_REFERENCE)) R6;
	egc_edispose = (void (**)(void)) R3;
	egc_copy = (void (**)(EIF_REFERENCE, EIF_REFERENCE)) R4;
	egc_is_equal = (EIF_BOOLEAN (**)(EIF_REFERENCE, EIF_REFERENCE)) R5;
	egc_ce_rname = egc_ce_rname_init;
	egc_fnbref = egc_fnbref_init;
	egc_fsize = egc_fsize_init;

	egc_system_name = "simodyssey1";
	egc_system_location = "C:\\Users\\Gavin Sit\\Documents\\School\\EECS 3311 Software Design\\Lab\\Lab 4\\simodyssey\\EIFGENs\\simodyssey1\\F_code";
	egc_compiler_tag = 38;
	egc_project_version = 1578970353;
	egc_has_old_special_semantic = 0;
	scount = 2019;

	egc_rcount = 1;
	egc_ridx = 0;
	egc_rlist = (char**) eif_malloc (sizeof(char*)*egc_rcount);
	egc_rcdt = (int32 *) eif_malloc (sizeof(int32)*egc_rcount);
	egc_rlist[0] = "ROOT.make";
	egc_rcdt[0] = 0;
	
	
	egc_platform_level = 0x00000D00;
	egc_routine_tables_init();
}

void egc_rcdt_init (void)
{
	if (egc_rcdt[0] == 0) {
		egc_rcdt[0] = 567; /* ROOT */
	}
}

#ifdef __cplusplus
}
#endif
